import { logout } from "@/utils/auth";
import { AntDesign, Feather, Ionicons, Octicons } from "@expo/vector-icons";

export const icons = {
  health: require("@/assets/icons/health.png"),
  "health-active": require("@/assets/icons/health-active.png"),
  gallery: require("@/assets/icons/gallery.png"),
  "gallery-active": require("@/assets/icons/gallery-active.png"),
  learn: require("@/assets/icons/learn.png"),
  "learn-active": require("@/assets/icons/learn-active.png"),
  explore: require("@/assets/icons/explore.png"),
  "explore-active": require("@/assets/icons/explore-active.png"),
  insights: require("@/assets/icons/insights.png"),
  "insights-active": require("@/assets/icons/insights-active.png"),
  user: require("@/assets/icons/user.png"),
  lock: require("@/assets/icons/lock.png"),
  card: require("@/assets/icons/card.png"),
  bell: require("@/assets/icons/bell.png"),
  language: require("@/assets/icons/language.png"),
  report: require("@/assets/icons/report.png"),
  contact: require("@/assets/icons/contact.png"),
  info: require("@/assets/icons/info.png"),
  logout: require("@/assets/icons/logout.png"),
  "pill-active": require("@/assets/icons/pill.png"),
  pill: require("@/assets/icons/pill-grey.png"),
  patch: require("@/assets/icons/patch-grey.png"),
  "patch-active": require("@/assets/icons/patch-active.png"),
  "push-pin": require("@/assets/icons/push-pin.png"),
  "stars-fill": require("@/assets/icons/stars-fill.png"),
  injection: require("@/assets/icons/injection.png"),
  "injection-active": require("@/assets/icons/injection-active.png"),
  gel: require("@/assets/icons/gel.png"),
  "gel-active": require("@/assets/icons/gel-active.png"),
  liquid: require("@/assets/icons/liquid.png"),
  "liquid-active": require("@/assets/icons/liquid-active.png"),
  tablet: require("@/assets/icons/tablet.png"),
  "tablet-active": require("@/assets/icons/tablet-active.png"),
  capsule: require("@/assets/icons/capsule.png"),
  "capsule-active": require("@/assets/icons/capsule-active.png"),
  pencil: require("@/assets/icons/pencil.png"),
  sun: require("@/assets/icons/day.png"),
  drug: require("@/assets/icons/drug.png"),
  location: require("@/assets/icons/location.png"),
  "health-report": require("@/assets/icons/health-report.png"),
  taken: require("@/assets/icons/taken.png"),
  skipped: require("@/assets/icons/skipped.png"),
  missed: require("@/assets/icons/missed.png"),
  pending: require("@/assets/icons/pending.png"),
  marker: require("@/assets/icons/marker.png"),
  hospital: require("@/assets/icons/hospital.png"),
  video: require("@/assets/icons/video.png"),
  article: require("@/assets/icons/article.png"),
  guide: require("@/assets/icons/guide.png"),
};
