import { logout } from "@/utils/auth";

export const icons = {
  health: require("@/assets/icons/health.png"),
  "health-active": require("@/assets/icons/health-active.png"),
  gallery: require("@/assets/icons/gallery.png"),
  "gallery-active": require("@/assets/icons/gallery-active.png"),
  learn: require("@/assets/icons/learn.png"),
  "learn-active": require("@/assets/icons/learn-active.png"),
  explore: require("@/assets/icons/explore.png"),
  "explore-active": require("@/assets/icons/explore-active.png"),
  insights: require("@/assets/icons/insights.png"),
  "insights-active": require("@/assets/icons/insights-active.png"),
  user: require("@/assets/icons/user.png"),
  lock: require("@/assets/icons/lock.png"),
  card: require("@/assets/icons/card.png"),
  bell: require("@/assets/icons/bell.png"),
  language: require("@/assets/icons/language.png"),
  report: require("@/assets/icons/report.png"),
  contact: require("@/assets/icons/contact.png"),
  info: require("@/assets/icons/info.png"),
  logout: require("@/assets/icons/logout.png"),
  pill: require("@/assets/icons/pill.png"),
  "pill-grey": require("@/assets/icons/pill-grey.png"),
  patch: require("@/assets/icons/patch.png"),
  "patch-grey": require("@/assets/icons/patch-grey.png"),
  "push-pin": require("@/assets/icons/push-pin.png"),
  "stars-fill": require("@/assets/icons/stars-fill.png"),
};
